services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/lib:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - zabbix-web

  db:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POST_USER}
      - POSTGRES_PASSWORD=${POST_PASS}
      - POSTGRES_DB=${POST_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    restart: always
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=${POST_USER}
      - POSTGRES_PASSWORD=${POST_PASS}
      - POSTGRES_DB=${POST_DB}
    depends_on:
      - db

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=${POST_USER}
      - POSTGRES_PASSWORD=${POST_PASS}
      - POSTGRES_DB=${POST_DB}
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Moscow
    depends_on:
      - zabbix-server
      - db

volumes:
  pg_data:
