all:
  children:
    zabbix_api:
      hosts:
        zabbix_api_host:
          ansible_host: 127.0.0.1

    huawei:
      hosts:
        huawei-core-1:
          ansible_host: 10.0.10.11
          ansible_user: netops
          ansible_password: "{{ vault_huawei_password }}"
          ansible_connection: network_cli

    ios:
      hosts:
        cisco-dist-1:
          ansible_host: 10.0.20.21
          ansible_user: netops
          ansible_password: "{{ vault_cisco_password }}"
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: "{{ vault_cisco_enable_password }}"
          ansible_connection: network_cli
          ansible_network_os: cisco.ios.ios

    mikrotik:
      hosts:
        rtr-br-1:
          ansible_host: 10.0.30.31
          ansible_user: admin
          ansible_password: "{{ vault_mikrotik_password }}"
          ansible_connection: network_cli
          ansible_network_os: community.routeros.routeros

    eltex:
      hosts:
        eltex-gw1:
          ansible_host: 10.0.40.41
          ansible_user: admin
          ansible_password: "{{ vault_eltex_password }}"
          ansible_connection: network_cli
